name: pointycastle
version: 2.0.0
author: Legion of the Bouncy Castle Inc.
description: A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library.
homepage: https://github.com/bcgit/pc-dart
environment:
  sdk: ">=2.1.1 <3.0.0"
#documentation: http://pointycastle.github.io/docs/

dev_dependencies:
  benchmark_harness: ">=1.0.5 <2.0.0"
  matcher: ">=0.12.0 <0.13.0"
  test: ">=0.12.30 <1.4.0"
  pedantic: ^1.9.0
