name: pointycastle
version: 3.9.1
description: A Dart library implementing cryptographic algorithms and primitives, modeled on the BouncyCastle library.
homepage: https://github.com/bcgit/pc-dart
topics:
 - crypto

environment:
  sdk: ^3.2.0

dependencies:
  collection: ^1.15.0
  convert: ^3.0.0
  js: '>=0.6.3 <0.8.0'

dev_dependencies:
  benchmark_harness: ^2.0.0
  lints: ^3.0.0
  test: ^1.16.0
